# =============================================================================
# Google Cloud Build Configuration for Blacklight
# Builds and deploys all services to Cloud Run with Auto-Scaling
# =============================================================================
#
# Trigger this build with:
#   gcloud builds submit --config=cloudbuild.yaml
#
# Or set up automatic triggers in Cloud Build for your GitHub repo

substitutions:
  _REGION: us-central1
  _PROJECT_ID: blacklight-477315
  _TAG: latest
  # Backend
  _BACKEND_SERVICE: blacklight-api
  _BACKEND_IMAGE: gcr.io/blacklight-477315/blacklight-api
  # Portal Frontend
  _PORTAL_SERVICE: blacklight-portal
  _PORTAL_IMAGE: gcr.io/blacklight-477315/blacklight-portal
  # CentralD Frontend
  _CENTRALD_SERVICE: blacklight-centrald
  _CENTRALD_IMAGE: gcr.io/blacklight-477315/blacklight-centrald
  # Frontend URLs (will be updated after first deployment)
  _BACKEND_URL: https://blacklight-api-oa27yqpx4a-uc.a.run.app

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  substitution_option: ALLOW_LOOSE

steps:
  # ==========================================================================
  # Step 1: Build Backend Docker image
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '${_BACKEND_IMAGE}:${_TAG}'
      - '-t'
      - '${_BACKEND_IMAGE}:latest'
      - '-f'
      - 'server/Dockerfile'
      - 'server'

  # ==========================================================================
  # Step 2: Build Portal Frontend Docker image
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-portal'
    args:
      - 'build'
      - '-t'
      - '${_PORTAL_IMAGE}:${_TAG}'
      - '-t'
      - '${_PORTAL_IMAGE}:latest'
      - '-f'
      - 'ui/portal/Dockerfile'
      - '--build-arg'
      - 'VITE_API_URL=${_BACKEND_URL}'
      - 'ui/portal'
    waitFor: ['-']  # Run in parallel with backend build

  # ==========================================================================
  # Step 3: Build CentralD Frontend Docker image
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-centrald'
    args:
      - 'build'
      - '-t'
      - '${_CENTRALD_IMAGE}:${_TAG}'
      - '-t'
      - '${_CENTRALD_IMAGE}:latest'
      - '-f'
      - 'ui/centralD/Dockerfile'
      - '--build-arg'
      - 'VITE_API_URL=${_BACKEND_URL}'
      - 'ui/centralD'
    waitFor: ['-']  # Run in parallel

  # ==========================================================================
  # Step 4: Push all images to Container Registry
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args: ['push', '--all-tags', '${_BACKEND_IMAGE}']
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-portal'
    args: ['push', '--all-tags', '${_PORTAL_IMAGE}']
    waitFor: ['build-portal']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-centrald'
    args: ['push', '--all-tags', '${_CENTRALD_IMAGE}']
    waitFor: ['build-centrald']

  # ==========================================================================
  # Step 5: Deploy Backend to Cloud Run (Auto-Scaling Enabled)
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE}'
      - '--image'
      - '${_BACKEND_IMAGE}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # ====== Auto-Scaling Configuration ======
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--cpu-throttling'
      # ====== Non-Sensitive Environment Variables ======
      - '--set-env-vars'
      - 'ENVIRONMENT=production,FLASK_ENV=production,FLASK_DEBUG=false,LOG_LEVEL=INFO,LOG_FORMAT=json,STORAGE_BACKEND=gcs,GCS_BUCKET_NAME=blacklight_freelance,GCS_PROJECT_ID=blacklight-477315,AI_PARSING_PROVIDER=gemini,GEMINI_MODEL=gemini-2.5-flash,MAX_FILE_SIZE_MB=10,ALLOWED_DOCUMENT_TYPES=pdf|doc|docx|jpg|jpeg|png,SIGNED_URL_EXPIRY_SECONDS=3600,SMTP_ENABLED=true,SMTP_HOST=smtp.gmail.com,SMTP_PORT=587,SMTP_USE_TLS=true,SMTP_FROM_EMAIL=sabariokg@gmail.com,SMTP_FROM_NAME=BlackLight HR,SMTP_USERNAME=sabariokg@gmail.com,INNGEST_DEV=false'
      # ====== Secrets from Secret Manager ======
      - '--set-secrets'
      - 'SECRET_KEY=blacklight-secret-key:latest,DATABASE_URL=blacklight-database-url:latest,REDIS_URL=blacklight-redis-url:latest,REDIS_CACHE_URL=blacklight-redis-url:latest,GEMINI_API_KEY=blacklight-gemini-api-key:latest,GOOGLE_API_KEY=blacklight-gemini-api-key:latest,GCS_CREDENTIALS_JSON=blacklight-gcs-credentials:latest,SMTP_PASSWORD=blacklight-smtp-password:latest,INNGEST_EVENT_KEY=blacklight-inngest-event-key:latest,INNGEST_SIGNING_KEY=blacklight-inngest-signing-key:latest'
    waitFor: ['push-backend']

  # ==========================================================================
  # Step 6: Deploy Portal Frontend to Cloud Run
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-portal'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_PORTAL_SERVICE}'
      - '--image'
      - '${_PORTAL_IMAGE}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '200'
    waitFor: ['push-portal', 'deploy-backend']

  # ==========================================================================
  # Step 7: Deploy CentralD Frontend to Cloud Run
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-centrald'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_CENTRALD_SERVICE}'
      - '--image'
      - '${_CENTRALD_IMAGE}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '200'
    waitFor: ['push-centrald', 'deploy-backend']

# Images to be pushed
images:
  - '${_BACKEND_IMAGE}:${_TAG}'
  - '${_BACKEND_IMAGE}:latest'
  - '${_PORTAL_IMAGE}:${_TAG}'
  - '${_PORTAL_IMAGE}:latest'
  - '${_CENTRALD_IMAGE}:${_TAG}'
  - '${_CENTRALD_IMAGE}:latest'

timeout: '1800s'  # 30 minutes total timeout
