"""add_unified_scoring_columns

Revision ID: 07b356029d4c
Revises: 835c736e66bf
Create Date: 2025-12-31 15:27:04.446258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07b356029d4c'
down_revision: Union[str, Sequence[str], None] = '835c736e66bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_job_matches', sa.Column('keyword_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('candidate_job_matches', sa.Column('match_grade', sa.String(length=5), nullable=True))
    op.add_column('candidate_job_matches', sa.Column('matched_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('candidate_job_matches', sa.Column('missing_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('candidate_job_matches', sa.Column('ai_compatibility_score', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('candidate_job_matches', sa.Column('ai_compatibility_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidate_job_matches', sa.Column('ai_scored_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_candidate_job_match_candidate_score'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_candidate_job_match_score_desc'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('ix_candidate_job_matches_match_grade'), 'candidate_job_matches', ['match_grade'], unique=False)
    op.drop_column('candidate_job_matches', 'salary_match_score')
    op.drop_column('candidate_job_matches', 'location_match_score')
    op.drop_index(op.f('idx_job_application_applied_at_desc'), table_name='job_applications')
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.drop_index(op.f('idx_job_import_batch_started_at_desc'), table_name='job_import_batches')
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.add_column('job_postings', sa.Column('extracted_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_job_posting_keywords'), table_name='job_postings', postgresql_using='gin')
    op.drop_index(op.f('idx_job_posting_posted_date_desc'), table_name='job_postings')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    op.drop_column('job_postings', 'keywords')
    op.drop_index(op.f('idx_submission_activity_submission_created'), table_name='submission_activities')
    op.create_index('idx_submission_activity_submission_created', 'submission_activities', ['submission_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_submission_submitted_at'), table_name='submissions')
    op.create_index('idx_submission_submitted_at', 'submissions', ['submitted_at'], unique=False, postgresql_ops={'submitted_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_submission_submitted_at', table_name='submissions', postgresql_ops={'submitted_at': 'DESC'})
    op.create_index(op.f('idx_submission_submitted_at'), 'submissions', [sa.literal_column('submitted_at DESC')], unique=False)
    op.drop_index('idx_submission_activity_submission_created', table_name='submission_activities', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_submission_activity_submission_created'), 'submission_activities', ['submission_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('job_postings', sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('idx_job_posting_posted_date_desc'), 'job_postings', [sa.literal_column('posted_date DESC')], unique=False)
    op.create_index(op.f('idx_job_posting_keywords'), 'job_postings', ['keywords'], unique=False, postgresql_using='gin')
    op.drop_column('job_postings', 'extracted_keywords')
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_job_import_batch_started_at_desc'), 'job_import_batches', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.create_index(op.f('idx_job_application_applied_at_desc'), 'job_applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.add_column('candidate_job_matches', sa.Column('location_match_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('candidate_job_matches', sa.Column('salary_match_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_candidate_job_matches_match_grade'), table_name='candidate_job_matches')
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_score_desc'), 'candidate_job_matches', [sa.literal_column('match_score DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_candidate_score'), 'candidate_job_matches', ['candidate_id', sa.literal_column('match_score DESC')], unique=False)
    op.drop_column('candidate_job_matches', 'ai_scored_at')
    op.drop_column('candidate_job_matches', 'ai_compatibility_details')
    op.drop_column('candidate_job_matches', 'ai_compatibility_score')
    op.drop_column('candidate_job_matches', 'missing_keywords')
    op.drop_column('candidate_job_matches', 'matched_keywords')
    op.drop_column('candidate_job_matches', 'match_grade')
    op.drop_column('candidate_job_matches', 'keyword_match_score')
    # ### end Alembic commands ###
