"""add position and notes to invitation

Revision ID: 0a26f62253f0
Revises: 011_add_document_storage
Create Date: 2025-11-11 10:45:13.874039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a26f62253f0'
down_revision = '011_add_document_storage'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_candidate_id', table_name='candidate_documents')
    op.drop_index('idx_documents_candidate_type', table_name='candidate_documents')
    op.drop_index('idx_documents_document_type', table_name='candidate_documents')
    op.drop_index('idx_documents_file_key', table_name='candidate_documents')
    op.drop_index('idx_documents_invitation_id', table_name='candidate_documents')
    op.drop_index('idx_documents_invitation_type', table_name='candidate_documents')
    op.drop_index('idx_documents_is_verified', table_name='candidate_documents')
    op.drop_index('idx_documents_tenant_id', table_name='candidate_documents')
    op.drop_index('idx_documents_tenant_type', table_name='candidate_documents')
    op.drop_index('idx_documents_uploaded_at', table_name='candidate_documents')
    op.drop_index('idx_documents_uploaded_by_id', table_name='candidate_documents')
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_documents', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_document_type'), 'candidate_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_candidate_documents_invitation_id'), 'candidate_documents', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_is_verified'), 'candidate_documents', ['is_verified'], unique=False)
    op.create_index(op.f('ix_candidate_documents_tenant_id'), 'candidate_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_uploaded_at'), 'candidate_documents', ['uploaded_at'], unique=False)
    op.add_column('candidate_invitations', sa.Column('position', sa.String(length=255), nullable=True))
    op.add_column('candidate_invitations', sa.Column('recruiter_notes', sa.Text(), nullable=True))
    op.drop_constraint('candidate_invitations_token_key', 'candidate_invitations', type_='unique')
    op.drop_index('idx_invitations_data_gin', table_name='candidate_invitations', postgresql_using='gin')
    op.drop_index('idx_invitations_email', table_name='candidate_invitations')
    op.drop_index('idx_invitations_expires_at', table_name='candidate_invitations')
    op.drop_index('idx_invitations_invited_by', table_name='candidate_invitations')
    op.drop_index('idx_invitations_status', table_name='candidate_invitations')
    op.drop_index('idx_invitations_tenant_email', table_name='candidate_invitations')
    op.drop_index('idx_invitations_tenant_id', table_name='candidate_invitations')
    op.drop_index('idx_invitations_tenant_status', table_name='candidate_invitations')
    op.drop_index('idx_invitations_token', table_name='candidate_invitations')
    op.create_index(op.f('ix_candidate_invitations_email'), 'candidate_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_expires_at'), 'candidate_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_invited_by_id'), 'candidate_invitations', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_reviewed_by_id'), 'candidate_invitations', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_status'), 'candidate_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_tenant_id'), 'candidate_invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_token'), 'candidate_invitations', ['token'], unique=True)
    op.drop_index('idx_candidates_invitation_id', table_name='candidates')
    op.drop_index('idx_candidates_onboarding_type', table_name='candidates')
    op.drop_constraint('candidates_invitation_id_fkey', 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'invitation_id')
    op.drop_column('candidates', 'onboarding_type')
    op.drop_index('idx_audit_logs_action', table_name='invitation_audit_logs')
    op.drop_index('idx_audit_logs_extra_data_gin', table_name='invitation_audit_logs', postgresql_using='gin')
    op.drop_index('idx_audit_logs_invitation_id', table_name='invitation_audit_logs')
    op.drop_index('idx_audit_logs_invitation_timestamp', table_name='invitation_audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='invitation_audit_logs')
    op.create_index(op.f('ix_invitation_audit_logs_action'), 'invitation_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_invitation_audit_logs_invitation_id'), 'invitation_audit_logs', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_invitation_audit_logs_timestamp'), 'invitation_audit_logs', ['timestamp'], unique=False)
    op.drop_index('idx_portal_users_role_id', table_name='portal_users')
    op.create_index(op.f('ix_portal_users_role_id'), 'portal_users', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_users_role_id'), table_name='portal_users')
    op.create_index('idx_portal_users_role_id', 'portal_users', ['role_id'], unique=False)
    op.drop_index(op.f('ix_invitation_audit_logs_timestamp'), table_name='invitation_audit_logs')
    op.drop_index(op.f('ix_invitation_audit_logs_invitation_id'), table_name='invitation_audit_logs')
    op.drop_index(op.f('ix_invitation_audit_logs_action'), table_name='invitation_audit_logs')
    op.create_index('idx_audit_logs_timestamp', 'invitation_audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_invitation_timestamp', 'invitation_audit_logs', ['invitation_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_logs_invitation_id', 'invitation_audit_logs', ['invitation_id'], unique=False)
    op.create_index('idx_audit_logs_extra_data_gin', 'invitation_audit_logs', ['extra_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_audit_logs_action', 'invitation_audit_logs', ['action'], unique=False)
    op.add_column('candidates', sa.Column('onboarding_type', sa.VARCHAR(length=50), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('invitation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('candidates_invitation_id_fkey', 'candidates', 'candidate_invitations', ['invitation_id'], ['id'])
    op.create_index('idx_candidates_onboarding_type', 'candidates', ['onboarding_type'], unique=False)
    op.create_index('idx_candidates_invitation_id', 'candidates', ['invitation_id'], unique=False)
    op.drop_index(op.f('ix_candidate_invitations_token'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_tenant_id'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_status'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_reviewed_by_id'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_invited_by_id'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_expires_at'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_email'), table_name='candidate_invitations')
    op.create_index('idx_invitations_token', 'candidate_invitations', ['token'], unique=False)
    op.create_index('idx_invitations_tenant_status', 'candidate_invitations', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_invitations_tenant_id', 'candidate_invitations', ['tenant_id'], unique=False)
    op.create_index('idx_invitations_tenant_email', 'candidate_invitations', ['tenant_id', 'email'], unique=False)
    op.create_index('idx_invitations_status', 'candidate_invitations', ['status'], unique=False)
    op.create_index('idx_invitations_invited_by', 'candidate_invitations', ['invited_by_id'], unique=False)
    op.create_index('idx_invitations_expires_at', 'candidate_invitations', ['expires_at'], unique=False)
    op.create_index('idx_invitations_email', 'candidate_invitations', ['email'], unique=False)
    op.create_index('idx_invitations_data_gin', 'candidate_invitations', ['invitation_data'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('candidate_invitations_token_key', 'candidate_invitations', ['token'])
    op.drop_column('candidate_invitations', 'recruiter_notes')
    op.drop_column('candidate_invitations', 'position')
    op.drop_index(op.f('ix_candidate_documents_uploaded_at'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_tenant_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_is_verified'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_invitation_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_document_type'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_documents')
    op.create_index('idx_documents_uploaded_by_id', 'candidate_documents', ['uploaded_by_id'], unique=False)
    op.create_index('idx_documents_uploaded_at', 'candidate_documents', ['uploaded_at'], unique=False)
    op.create_index('idx_documents_tenant_type', 'candidate_documents', ['tenant_id', 'document_type'], unique=False)
    op.create_index('idx_documents_tenant_id', 'candidate_documents', ['tenant_id'], unique=False)
    op.create_index('idx_documents_is_verified', 'candidate_documents', ['is_verified'], unique=False)
    op.create_index('idx_documents_invitation_type', 'candidate_documents', ['invitation_id', 'document_type'], unique=False)
    op.create_index('idx_documents_invitation_id', 'candidate_documents', ['invitation_id'], unique=False)
    op.create_index('idx_documents_file_key', 'candidate_documents', ['file_key'], unique=False)
    op.create_index('idx_documents_document_type', 'candidate_documents', ['document_type'], unique=False)
    op.create_index('idx_documents_candidate_type', 'candidate_documents', ['candidate_id', 'document_type'], unique=False)
    op.create_index('idx_documents_candidate_id', 'candidate_documents', ['candidate_id'], unique=False)
    # ### end Alembic commands ###
