"""add_scraper_credentials_table

Revision ID: 174cef520a2c
Revises: 626103848f2f
Create Date: 2026-01-05 12:12:54.799198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174cef520a2c'
down_revision: Union[str, Sequence[str], None] = '626103848f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_session_id', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_message', sa.Text(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scraper_credentials_available', 'scraper_credentials', ['platform', 'status', 'cooldown_until'], unique=False)
    op.create_index('idx_scraper_credentials_platform_status', 'scraper_credentials', ['platform', 'status'], unique=False)
    op.create_index(op.f('ix_scraper_credentials_platform'), 'scraper_credentials', ['platform'], unique=False)
    op.create_index(op.f('ix_scraper_credentials_status'), 'scraper_credentials', ['status'], unique=False)
    op.drop_index(op.f('idx_candidate_job_match_candidate_score'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_candidate_job_match_score_desc'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_job_application_applied_at_desc'), table_name='job_applications')
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.drop_index(op.f('idx_job_import_batch_started_at_desc'), table_name='job_import_batches')
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_index(op.f('idx_job_posting_posted_date_desc'), table_name='job_postings')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    op.drop_index(op.f('idx_submission_activity_submission_created'), table_name='submission_activities')
    op.create_index('idx_submission_activity_submission_created', 'submission_activities', ['submission_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_submission_submitted_at'), table_name='submissions')
    op.create_index('idx_submission_submitted_at', 'submissions', ['submitted_at'], unique=False, postgresql_ops={'submitted_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_submission_submitted_at', table_name='submissions', postgresql_ops={'submitted_at': 'DESC'})
    op.create_index(op.f('idx_submission_submitted_at'), 'submissions', [sa.literal_column('submitted_at DESC')], unique=False)
    op.drop_index('idx_submission_activity_submission_created', table_name='submission_activities', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_submission_activity_submission_created'), 'submission_activities', ['submission_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('idx_job_posting_posted_date_desc'), 'job_postings', [sa.literal_column('posted_date DESC')], unique=False)
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_job_import_batch_started_at_desc'), 'job_import_batches', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.create_index(op.f('idx_job_application_applied_at_desc'), 'job_applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_score_desc'), 'candidate_job_matches', [sa.literal_column('match_score DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_candidate_score'), 'candidate_job_matches', ['candidate_id', sa.literal_column('match_score DESC')], unique=False)
    op.drop_index(op.f('ix_scraper_credentials_status'), table_name='scraper_credentials')
    op.drop_index(op.f('ix_scraper_credentials_platform'), table_name='scraper_credentials')
    op.drop_index('idx_scraper_credentials_platform_status', table_name='scraper_credentials')
    op.drop_index('idx_scraper_credentials_available', table_name='scraper_credentials')
    op.drop_table('scraper_credentials')
    # ### end Alembic commands ###
