"""add submission tracking tables

Revision ID: 25325927967a
Revises: 32ef65dd4ec8
Create Date: 2025-12-30 10:45:23.701203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25325927967a'
down_revision: Union[str, Sequence[str], None] = '32ef65dd4ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('status_changed_by_id', sa.Integer(), nullable=True),
    sa.Column('vendor_company', sa.String(length=255), nullable=True),
    sa.Column('vendor_contact_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_contact_email', sa.String(length=255), nullable=True),
    sa.Column('vendor_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('client_company', sa.String(length=255), nullable=True),
    sa.Column('bill_rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pay_rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('rate_type', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('submission_notes', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('resume_version_used', sa.String(length=255), nullable=True),
    sa.Column('tailored_resume_id', sa.Integer(), nullable=True),
    sa.Column('interview_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('interview_location', sa.String(length=500), nullable=True),
    sa.Column('interview_notes', sa.Text(), nullable=True),
    sa.Column('interview_feedback', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_stage', sa.String(length=50), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('placement_start_date', sa.DateTime(), nullable=True),
    sa.Column('placement_end_date', sa.DateTime(), nullable=True),
    sa.Column('placement_duration_months', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_changed_by_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tailored_resume_id'], ['tailored_resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submission_submitted_at', 'submissions', ['submitted_at'], unique=False, postgresql_ops={'submitted_at': 'DESC'})
    op.create_index('idx_submission_submitted_by', 'submissions', ['submitted_by_user_id', 'status'], unique=False)
    op.create_index('idx_submission_tenant_status', 'submissions', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_submission_unique', 'submissions', ['candidate_id', 'job_posting_id', 'tenant_id'], unique=True)
    op.create_index(op.f('ix_submissions_candidate_id'), 'submissions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_submissions_job_posting_id'), 'submissions', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_submitted_by_user_id'), 'submissions', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_submissions_tenant_id'), 'submissions', ['tenant_id'], unique=False)
    op.create_table('submission_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submission_activity_submission_created', 'submission_activities', ['submission_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_submission_activity_type', 'submission_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_submission_activities_activity_type'), 'submission_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_submission_activities_created_by_id'), 'submission_activities', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_submission_activities_submission_id'), 'submission_activities', ['submission_id'], unique=False)
    op.drop_index(op.f('idx_candidate_job_match_candidate_score'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_candidate_job_match_score_desc'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_job_application_applied_at_desc'), table_name='job_applications')
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.drop_index(op.f('idx_job_import_batch_started_at_desc'), table_name='job_import_batches')
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_index(op.f('idx_job_posting_posted_date_desc'), table_name='job_postings')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('idx_job_posting_posted_date_desc'), 'job_postings', [sa.literal_column('posted_date DESC')], unique=False)
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_job_import_batch_started_at_desc'), 'job_import_batches', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.create_index(op.f('idx_job_application_applied_at_desc'), 'job_applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_score_desc'), 'candidate_job_matches', [sa.literal_column('match_score DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_candidate_score'), 'candidate_job_matches', ['candidate_id', sa.literal_column('match_score DESC')], unique=False)
    op.drop_index(op.f('ix_submission_activities_submission_id'), table_name='submission_activities')
    op.drop_index(op.f('ix_submission_activities_created_by_id'), table_name='submission_activities')
    op.drop_index(op.f('ix_submission_activities_activity_type'), table_name='submission_activities')
    op.drop_index('idx_submission_activity_type', table_name='submission_activities')
    op.drop_index('idx_submission_activity_submission_created', table_name='submission_activities', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('submission_activities')
    op.drop_index(op.f('ix_submissions_tenant_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submitted_by_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_job_posting_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_candidate_id'), table_name='submissions')
    op.drop_index('idx_submission_unique', table_name='submissions')
    op.drop_index('idx_submission_tenant_status', table_name='submissions')
    op.drop_index('idx_submission_submitted_by', table_name='submissions')
    op.drop_index('idx_submission_submitted_at', table_name='submissions', postgresql_ops={'submitted_at': 'DESC'})
    op.drop_table('submissions')
    # ### end Alembic commands ###
