"""add_cascade_to_invitation_candidate_fk

Revision ID: 3be0423032a8
Revises: 4da0bfd99243
Create Date: 2025-11-14 16:04:25.168422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be0423032a8'
down_revision: Union[str, Sequence[str], None] = '4da0bfd99243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('candidate_invitations_candidate_id_fkey'), 'candidate_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_invitations', 'candidates', ['candidate_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_invitations_candidate_id_fkey'), 'candidate_invitations', 'candidates', ['candidate_id'], ['id'])
    # ### end Alembic commands ###
