"""add_scrape_queue_and_role_normalization_tables

Revision ID: 402591f219c9
Revises: 6d7c05c701c0
Create Date: 2025-12-10 14:55:22.478866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '402591f219c9'
down_revision: Union[str, Sequence[str], None] = '6d7c05c701c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('queue_status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('total_jobs_scraped', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_global_roles_category', 'global_roles', ['category'], unique=False)
    op.create_index('idx_global_roles_embedding', 'global_roles', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 50}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_global_roles_queue', 'global_roles', ['queue_status', 'priority', 'candidate_count'], unique=False)
    op.create_index(op.f('ix_global_roles_name'), 'global_roles', ['name'], unique=True)
    op.create_index(op.f('ix_global_roles_queue_status'), 'global_roles', ['queue_status'], unique=False)
    op.create_table('scraper_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('total_jobs_imported', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['pm_admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by'], ['pm_admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scraper_api_keys_active', 'scraper_api_keys', ['is_active'], unique=False)
    op.create_index('idx_scraper_api_keys_name', 'scraper_api_keys', ['name'], unique=False)
    op.create_index(op.f('ix_scraper_api_keys_is_active'), 'scraper_api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_scraper_api_keys_key_hash'), 'scraper_api_keys', ['key_hash'], unique=True)
    op.create_table('scrape_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('scraper_key_id', sa.Integer(), nullable=True),
    sa.Column('scraper_name', sa.String(length=100), nullable=True),
    sa.Column('global_role_id', sa.Integer(), nullable=True),
    sa.Column('role_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_imported', sa.Integer(), nullable=True),
    sa.Column('jobs_skipped', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['global_role_id'], ['global_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraper_key_id'], ['scraper_api_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_scrape_sessions_role', 'scrape_sessions', ['global_role_id'], unique=False)
    op.create_index('idx_scrape_sessions_session', 'scrape_sessions', ['session_id'], unique=False)
    op.create_index('idx_scrape_sessions_started', 'scrape_sessions', ['started_at'], unique=False)
    op.create_index('idx_scrape_sessions_status', 'scrape_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_scrape_sessions_global_role_id'), 'scrape_sessions', ['global_role_id'], unique=False)
    op.create_index(op.f('ix_scrape_sessions_scraper_key_id'), 'scrape_sessions', ['scraper_key_id'], unique=False)
    op.create_index(op.f('ix_scrape_sessions_status'), 'scrape_sessions', ['status'], unique=False)
    op.create_table('role_job_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_role_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['global_role_id'], ['global_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_role_id', 'job_posting_id', name='uq_role_job_mapping')
    )
    op.create_index('idx_role_job_mapping_job', 'role_job_mappings', ['job_posting_id'], unique=False)
    op.create_index('idx_role_job_mapping_role', 'role_job_mappings', ['global_role_id'], unique=False)
    op.create_index(op.f('ix_role_job_mappings_global_role_id'), 'role_job_mappings', ['global_role_id'], unique=False)
    op.create_index(op.f('ix_role_job_mappings_job_posting_id'), 'role_job_mappings', ['job_posting_id'], unique=False)
    op.create_table('candidate_global_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('global_role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_role_id'], ['global_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'global_role_id', name='uq_candidate_global_role')
    )
    op.create_index('idx_candidate_global_roles_candidate', 'candidate_global_roles', ['candidate_id'], unique=False)
    op.create_index('idx_candidate_global_roles_role', 'candidate_global_roles', ['global_role_id'], unique=False)
    op.create_index(op.f('ix_candidate_global_roles_candidate_id'), 'candidate_global_roles', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_global_roles_global_role_id'), 'candidate_global_roles', ['global_role_id'], unique=False)
    op.drop_index(op.f('idx_candidate_job_match_candidate_score'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_candidate_job_match_score_desc'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_job_application_applied_at_desc'), table_name='job_applications')
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.drop_index(op.f('idx_job_import_batch_started_at_desc'), table_name='job_import_batches')
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.add_column('job_postings', sa.Column('scraped_by_key_id', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('scrape_session_id', sa.UUID(), nullable=True))
    op.add_column('job_postings', sa.Column('normalized_role_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_job_posting_posted_date_desc'), table_name='job_postings')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('ix_job_postings_normalized_role_id'), 'job_postings', ['normalized_role_id'], unique=False)
    op.create_index(op.f('ix_job_postings_scrape_session_id'), 'job_postings', ['scrape_session_id'], unique=False)
    op.create_index(op.f('ix_job_postings_scraped_by_key_id'), 'job_postings', ['scraped_by_key_id'], unique=False)
    op.create_foreign_key(None, 'job_postings', 'global_roles', ['normalized_role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'job_postings', 'scraper_api_keys', ['scraped_by_key_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_index(op.f('ix_job_postings_scraped_by_key_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_scrape_session_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_normalized_role_id'), table_name='job_postings')
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('idx_job_posting_posted_date_desc'), 'job_postings', [sa.literal_column('posted_date DESC')], unique=False)
    op.drop_column('job_postings', 'normalized_role_id')
    op.drop_column('job_postings', 'scrape_session_id')
    op.drop_column('job_postings', 'scraped_by_key_id')
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_job_import_batch_started_at_desc'), 'job_import_batches', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.create_index(op.f('idx_job_application_applied_at_desc'), 'job_applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_score_desc'), 'candidate_job_matches', [sa.literal_column('match_score DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_candidate_score'), 'candidate_job_matches', ['candidate_id', sa.literal_column('match_score DESC')], unique=False)
    op.drop_index(op.f('ix_candidate_global_roles_global_role_id'), table_name='candidate_global_roles')
    op.drop_index(op.f('ix_candidate_global_roles_candidate_id'), table_name='candidate_global_roles')
    op.drop_index('idx_candidate_global_roles_role', table_name='candidate_global_roles')
    op.drop_index('idx_candidate_global_roles_candidate', table_name='candidate_global_roles')
    op.drop_table('candidate_global_roles')
    op.drop_index(op.f('ix_role_job_mappings_job_posting_id'), table_name='role_job_mappings')
    op.drop_index(op.f('ix_role_job_mappings_global_role_id'), table_name='role_job_mappings')
    op.drop_index('idx_role_job_mapping_role', table_name='role_job_mappings')
    op.drop_index('idx_role_job_mapping_job', table_name='role_job_mappings')
    op.drop_table('role_job_mappings')
    op.drop_index(op.f('ix_scrape_sessions_status'), table_name='scrape_sessions')
    op.drop_index(op.f('ix_scrape_sessions_scraper_key_id'), table_name='scrape_sessions')
    op.drop_index(op.f('ix_scrape_sessions_global_role_id'), table_name='scrape_sessions')
    op.drop_index('idx_scrape_sessions_status', table_name='scrape_sessions')
    op.drop_index('idx_scrape_sessions_started', table_name='scrape_sessions')
    op.drop_index('idx_scrape_sessions_session', table_name='scrape_sessions')
    op.drop_index('idx_scrape_sessions_role', table_name='scrape_sessions')
    op.drop_table('scrape_sessions')
    op.drop_index(op.f('ix_scraper_api_keys_key_hash'), table_name='scraper_api_keys')
    op.drop_index(op.f('ix_scraper_api_keys_is_active'), table_name='scraper_api_keys')
    op.drop_index('idx_scraper_api_keys_name', table_name='scraper_api_keys')
    op.drop_index('idx_scraper_api_keys_active', table_name='scraper_api_keys')
    op.drop_table('scraper_api_keys')
    op.drop_index(op.f('ix_global_roles_queue_status'), table_name='global_roles')
    op.drop_index(op.f('ix_global_roles_name'), table_name='global_roles')
    op.drop_index('idx_global_roles_queue', table_name='global_roles')
    op.drop_index('idx_global_roles_embedding', table_name='global_roles', postgresql_using='ivfflat', postgresql_with={'lists': 50}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_global_roles_category', table_name='global_roles')
    op.drop_table('global_roles')
    # ### end Alembic commands ###
