"""add_is_visible_to_all_team_to_candidates

Revision ID: 4d4b7db30f02
Revises: aa926dcab9c0
Create Date: 2025-11-28 11:57:10.436658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4b7db30f02'
down_revision: Union[str, Sequence[str], None] = 'aa926dcab9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_candidate_job_match_candidate_score'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_candidate_job_match_score_desc'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.add_column('candidates', sa.Column('is_visible_to_all_team', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('idx_job_application_applied_at_desc'), table_name='job_applications')
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.drop_index(op.f('idx_job_import_batch_started_at_desc'), table_name='job_import_batches')
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_index(op.f('idx_job_posting_posted_date_desc'), table_name='job_postings')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('idx_job_posting_posted_date_desc'), 'job_postings', [sa.literal_column('posted_date DESC')], unique=False)
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_job_import_batch_started_at_desc'), 'job_import_batches', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.create_index(op.f('idx_job_application_applied_at_desc'), 'job_applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.drop_column('candidates', 'is_visible_to_all_team')
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_score_desc'), 'candidate_job_matches', [sa.literal_column('match_score DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_candidate_score'), 'candidate_job_matches', ['candidate_id', sa.literal_column('match_score DESC')], unique=False)
    # ### end Alembic commands ###
