"""add_candidate_assignment_schema

Revision ID: 4da0bfd99243
Revises: 59c7a1440027
Create Date: 2025-11-13 12:02:01.836465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da0bfd99243'
down_revision: Union[str, Sequence[str], None] = '59c7a1440027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('previous_assignee_id', sa.Integer(), nullable=True),
    sa.Column('assignment_reason', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_assigned_to', 'candidate_assignments', ['assigned_to_user_id'], unique=False)
    op.create_index('idx_assignment_candidate_id', 'candidate_assignments', ['candidate_id'], unique=False)
    op.create_index('idx_assignment_status', 'candidate_assignments', ['status'], unique=False)
    op.create_index('idx_assignment_type', 'candidate_assignments', ['assignment_type'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_assigned_by_user_id'), 'candidate_assignments', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_assigned_to_user_id'), 'candidate_assignments', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_candidate_id'), 'candidate_assignments', ['candidate_id'], unique=False)
    op.create_table('assignment_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['candidate_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_is_read', 'assignment_notifications', ['is_read'], unique=False)
    op.create_index('idx_notification_type', 'assignment_notifications', ['notification_type'], unique=False)
    op.create_index('idx_notification_user_id', 'assignment_notifications', ['user_id'], unique=False)
    op.create_index('idx_notification_user_read', 'assignment_notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_assignment_notifications_assignment_id'), 'assignment_notifications', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_notifications_user_id'), 'assignment_notifications', ['user_id'], unique=False)
    op.add_column('candidates', sa.Column('onboarding_status', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('onboarded_by_user_id', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('onboarded_at', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('rejected_by_user_id', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('recruiter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'portal_users', ['approved_by_user_id'], ['id'])
    op.create_foreign_key(None, 'candidates', 'portal_users', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'candidates', 'portal_users', ['rejected_by_user_id'], ['id'])
    op.create_foreign_key(None, 'candidates', 'portal_users', ['onboarded_by_user_id'], ['id'])
    op.create_foreign_key(None, 'candidates', 'portal_users', ['recruiter_id'], ['id'])
    op.add_column('portal_users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_portal_users_manager_id'), 'portal_users', ['manager_id'], unique=False)
    op.create_foreign_key(None, 'portal_users', 'portal_users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portal_users', type_='foreignkey')
    op.drop_index(op.f('ix_portal_users_manager_id'), table_name='portal_users')
    op.drop_column('portal_users', 'manager_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'recruiter_id')
    op.drop_column('candidates', 'manager_id')
    op.drop_column('candidates', 'rejection_reason')
    op.drop_column('candidates', 'rejected_at')
    op.drop_column('candidates', 'rejected_by_user_id')
    op.drop_column('candidates', 'approved_at')
    op.drop_column('candidates', 'approved_by_user_id')
    op.drop_column('candidates', 'onboarded_at')
    op.drop_column('candidates', 'onboarded_by_user_id')
    op.drop_column('candidates', 'onboarding_status')
    op.drop_index(op.f('ix_assignment_notifications_user_id'), table_name='assignment_notifications')
    op.drop_index(op.f('ix_assignment_notifications_assignment_id'), table_name='assignment_notifications')
    op.drop_index('idx_notification_user_read', table_name='assignment_notifications')
    op.drop_index('idx_notification_user_id', table_name='assignment_notifications')
    op.drop_index('idx_notification_type', table_name='assignment_notifications')
    op.drop_index('idx_notification_is_read', table_name='assignment_notifications')
    op.drop_table('assignment_notifications')
    op.drop_index(op.f('ix_candidate_assignments_candidate_id'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_assigned_to_user_id'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_assigned_by_user_id'), table_name='candidate_assignments')
    op.drop_index('idx_assignment_type', table_name='candidate_assignments')
    op.drop_index('idx_assignment_status', table_name='candidate_assignments')
    op.drop_index('idx_assignment_candidate_id', table_name='candidate_assignments')
    op.drop_index('idx_assignment_assigned_to', table_name='candidate_assignments')
    op.drop_table('candidate_assignments')
    # ### end Alembic commands ###
