"""Add custom plan support to subscription_plan

Revision ID: 6428815cabb9
Revises: 34fbd9a19f62
Create Date: 2026-01-25 16:59:40.207934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6428815cabb9'
down_revision: Union[str, Sequence[str], None] = '34fbd9a19f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_candidate_job_match_candidate_score'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_candidate_job_match_score_desc'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_job_application_applied_at_desc'), table_name='job_applications')
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.drop_index(op.f('idx_job_import_batch_started_at_desc'), table_name='job_import_batches')
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_index(op.f('idx_job_posting_posted_date_desc'), table_name='job_postings')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    op.drop_index(op.f('idx_submission_activity_submission_created'), table_name='submission_activities')
    op.create_index('idx_submission_activity_submission_created', 'submission_activities', ['submission_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_submission_submitted_at'), table_name='submissions')
    op.create_index('idx_submission_submitted_at', 'submissions', ['submitted_at'], unique=False, postgresql_ops={'submitted_at': 'DESC'})
    
    op.add_column('subscription_plans', sa.Column('is_custom', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('subscription_plans', sa.Column('custom_for_tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subscription_plans_custom_for_tenant_id'), 'subscription_plans', ['custom_for_tenant_id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_is_custom'), 'subscription_plans', ['is_custom'], unique=False)
    op.create_foreign_key(None, 'subscription_plans', 'tenants', ['custom_for_tenant_id'], ['id'], ondelete='CASCADE')
    
    op.alter_column('subscription_plans', 'is_custom', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_plans', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_plans_is_custom'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_custom_for_tenant_id'), table_name='subscription_plans')
    op.drop_column('subscription_plans', 'custom_for_tenant_id')
    op.drop_column('subscription_plans', 'is_custom')
    op.drop_index('idx_submission_submitted_at', table_name='submissions', postgresql_ops={'submitted_at': 'DESC'})
    op.create_index(op.f('idx_submission_submitted_at'), 'submissions', [sa.literal_column('submitted_at DESC')], unique=False)
    op.drop_index('idx_submission_activity_submission_created', table_name='submission_activities', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_submission_activity_submission_created'), 'submission_activities', ['submission_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('idx_job_posting_posted_date_desc'), 'job_postings', [sa.literal_column('posted_date DESC')], unique=False)
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_job_import_batch_started_at_desc'), 'job_import_batches', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.create_index(op.f('idx_job_application_applied_at_desc'), 'job_applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_score_desc'), 'candidate_job_matches', [sa.literal_column('match_score DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_candidate_score'), 'candidate_job_matches', ['candidate_id', sa.literal_column('match_score DESC')], unique=False)
    # ### end Alembic commands ###
