"""initial schema

Revision ID: 6d7c05c701c0
Revises: 
Create Date: 2025-11-29 20:57:57.529432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '6d7c05c701c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure pgvector extension is available
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('audit_logs',
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('job_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('import_source', sa.String(length=100), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('new_jobs', sa.Integer(), nullable=True),
    sa.Column('updated_jobs', sa.Integer(), nullable=True),
    sa.Column('failed_jobs', sa.Integer(), nullable=True),
    sa.Column('import_status', sa.String(length=50), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_import_batch_platform', 'job_import_batches', ['platform'], unique=False)
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.create_index('idx_job_import_batch_status', 'job_import_batches', ['import_status'], unique=False)
    op.create_index(op.f('ix_job_import_batches_batch_id'), 'job_import_batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_job_import_batches_import_status'), 'job_import_batches', ['import_status'], unique=False)
    op.create_index(op.f('ix_job_import_batches_platform'), 'job_import_batches', ['platform'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_range', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('experience_required', sa.String(length=100), nullable=True),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_posting_embedding', 'job_postings', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_job_posting_keywords', 'job_postings', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_job_posting_platform_external', 'job_postings', ['platform', 'external_job_id'], unique=True)
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    op.create_index('idx_job_posting_skills', 'job_postings', ['skills'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_job_postings_import_batch_id'), 'job_postings', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_job_postings_is_remote'), 'job_postings', ['is_remote'], unique=False)
    op.create_index(op.f('ix_job_postings_location'), 'job_postings', ['location'], unique=False)
    op.create_index(op.f('ix_job_postings_platform'), 'job_postings', ['platform'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_date'), 'job_postings', ['posted_date'], unique=False)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('pm_admin_users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pm_admin_users_email'), 'pm_admin_users', ['email'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_candidates', sa.Integer(), nullable=False),
    sa.Column('max_jobs', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('company_email', sa.String(length=120), nullable=False),
    sa.Column('company_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='tenantstatus'), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=False),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', name='billingcycle'), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_email')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('ix_tenants_subscription_plan_id'), 'tenants', ['subscription_plan_id'], unique=False)
    op.create_table('portal_users',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portal_user_email', 'portal_users', ['email'], unique=False)
    op.create_index('idx_portal_user_tenant_id', 'portal_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_portal_users_email'), 'portal_users', ['email'], unique=True)
    op.create_index(op.f('ix_portal_users_manager_id'), 'portal_users', ['manager_id'], unique=False)
    op.create_index(op.f('ix_portal_users_tenant_id'), 'portal_users', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(is_system_role = true AND tenant_id IS NULL) OR (is_system_role = false)', name='ck_roles_system_role_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name')
    )
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_roles_is_system_role'), 'roles', ['is_system_role'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('tenant_subscription_history',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', name='billingcycle'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['pm_admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subscription_history_subscription_plan_id'), 'tenant_subscription_history', ['subscription_plan_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscription_history_tenant_id'), 'tenant_subscription_history', ['tenant_id'], unique=False)
    op.create_table('candidates',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('onboarding_status', sa.String(length=50), nullable=True),
    sa.Column('onboarded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.Column('is_visible_to_all_team', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resume_file_key', sa.String(length=1000), nullable=True),
    sa.Column('resume_storage_backend', sa.String(length=20), nullable=True),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('resume_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('resume_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('current_title', sa.String(length=200), nullable=True),
    sa.Column('total_experience_years', sa.Integer(), nullable=True),
    sa.Column('notice_period', sa.String(length=100), nullable=True),
    sa.Column('expected_salary', sa.String(length=100), nullable=True),
    sa.Column('professional_summary', sa.Text(), nullable=True),
    sa.Column('preferred_locations', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('certifications', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_roles', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_resume_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['onboarded_by_user_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('candidate_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('previous_assignee_id', sa.Integer(), nullable=True),
    sa.Column('assignment_reason', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_assigned_to', 'candidate_assignments', ['assigned_to_user_id'], unique=False)
    op.create_index('idx_assignment_candidate_id', 'candidate_assignments', ['candidate_id'], unique=False)
    op.create_index('idx_assignment_status', 'candidate_assignments', ['status'], unique=False)
    op.create_index('idx_assignment_type', 'candidate_assignments', ['assignment_type'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_assigned_by_user_id'), 'candidate_assignments', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_assigned_to_user_id'), 'candidate_assignments', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_candidate_id'), 'candidate_assignments', ['candidate_id'], unique=False)
    op.create_table('candidate_invitations',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('recruiter_notes', sa.Text(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('invitation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_invitations_email'), 'candidate_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_expires_at'), 'candidate_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_invited_by_id'), 'candidate_invitations', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_reviewed_by_id'), 'candidate_invitations', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_status'), 'candidate_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_tenant_id'), 'candidate_invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_candidate_invitations_token'), 'candidate_invitations', ['token'], unique=True)
    op.create_table('candidate_job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('skill_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('experience_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('location_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('salary_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('semantic_similarity', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('matched_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('missing_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('match_reasons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.create_index('idx_candidate_job_match_unique', 'candidate_job_matches', ['candidate_id', 'job_posting_id'], unique=True)
    op.create_index(op.f('ix_candidate_job_matches_candidate_id'), 'candidate_job_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_job_posting_id'), 'candidate_job_matches', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_match_score'), 'candidate_job_matches', ['match_score'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_status'), 'candidate_job_matches', ['status'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('applied_via', sa.String(length=50), nullable=True),
    sa.Column('applied_by_user_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('screened_at', sa.DateTime(), nullable=True),
    sa.Column('interviewed_at', sa.DateTime(), nullable=True),
    sa.Column('offer_received_at', sa.DateTime(), nullable=True),
    sa.Column('offer_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.create_index('idx_job_application_candidate_status', 'job_applications', ['candidate_id', 'application_status'], unique=False)
    op.create_index('idx_job_application_unique', 'job_applications', ['candidate_id', 'job_posting_id'], unique=True)
    op.create_index(op.f('ix_job_applications_application_status'), 'job_applications', ['application_status'], unique=False)
    op.create_index(op.f('ix_job_applications_candidate_id'), 'job_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_applications_job_posting_id'), 'job_applications', ['job_posting_id'], unique=False)
    op.create_table('assignment_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['candidate_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_is_read', 'assignment_notifications', ['is_read'], unique=False)
    op.create_index('idx_notification_type', 'assignment_notifications', ['notification_type'], unique=False)
    op.create_index('idx_notification_user_id', 'assignment_notifications', ['user_id'], unique=False)
    op.create_index('idx_notification_user_read', 'assignment_notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_assignment_notifications_assignment_id'), 'assignment_notifications', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_notifications_user_id'), 'assignment_notifications', ['user_id'], unique=False)
    op.create_table('candidate_documents',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('invitation_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_key', sa.String(length=1000), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitation_id'], ['candidate_invitations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['portal_users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['portal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_documents', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_document_type'), 'candidate_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_candidate_documents_invitation_id'), 'candidate_documents', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_is_verified'), 'candidate_documents', ['is_verified'], unique=False)
    op.create_index(op.f('ix_candidate_documents_tenant_id'), 'candidate_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_uploaded_at'), 'candidate_documents', ['uploaded_at'], unique=False)
    op.create_table('invitation_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['candidate_invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_audit_logs_action'), 'invitation_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_invitation_audit_logs_invitation_id'), 'invitation_audit_logs', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_invitation_audit_logs_timestamp'), 'invitation_audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_audit_logs_timestamp'), table_name='invitation_audit_logs')
    op.drop_index(op.f('ix_invitation_audit_logs_invitation_id'), table_name='invitation_audit_logs')
    op.drop_index(op.f('ix_invitation_audit_logs_action'), table_name='invitation_audit_logs')
    op.drop_table('invitation_audit_logs')
    op.drop_index(op.f('ix_candidate_documents_uploaded_at'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_tenant_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_is_verified'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_invitation_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_document_type'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_documents')
    op.drop_table('candidate_documents')
    op.drop_index(op.f('ix_assignment_notifications_user_id'), table_name='assignment_notifications')
    op.drop_index(op.f('ix_assignment_notifications_assignment_id'), table_name='assignment_notifications')
    op.drop_index('idx_notification_user_read', table_name='assignment_notifications')
    op.drop_index('idx_notification_user_id', table_name='assignment_notifications')
    op.drop_index('idx_notification_type', table_name='assignment_notifications')
    op.drop_index('idx_notification_is_read', table_name='assignment_notifications')
    op.drop_table('assignment_notifications')
    op.drop_index(op.f('ix_job_applications_job_posting_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_candidate_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_application_status'), table_name='job_applications')
    op.drop_index('idx_job_application_unique', table_name='job_applications')
    op.drop_index('idx_job_application_candidate_status', table_name='job_applications')
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_candidate_job_matches_status'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_match_score'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_job_posting_id'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_candidate_id'), table_name='candidate_job_matches')
    op.drop_index('idx_candidate_job_match_unique', table_name='candidate_job_matches')
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.drop_table('candidate_job_matches')
    op.drop_index(op.f('ix_candidate_invitations_token'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_tenant_id'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_status'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_reviewed_by_id'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_invited_by_id'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_expires_at'), table_name='candidate_invitations')
    op.drop_index(op.f('ix_candidate_invitations_email'), table_name='candidate_invitations')
    op.drop_table('candidate_invitations')
    op.drop_index(op.f('ix_candidate_assignments_candidate_id'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_assigned_to_user_id'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_assigned_by_user_id'), table_name='candidate_assignments')
    op.drop_index('idx_assignment_type', table_name='candidate_assignments')
    op.drop_index('idx_assignment_status', table_name='candidate_assignments')
    op.drop_index('idx_assignment_candidate_id', table_name='candidate_assignments')
    op.drop_index('idx_assignment_assigned_to', table_name='candidate_assignments')
    op.drop_table('candidate_assignments')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_tenant_subscription_history_tenant_id'), table_name='tenant_subscription_history')
    op.drop_index(op.f('ix_tenant_subscription_history_subscription_plan_id'), table_name='tenant_subscription_history')
    op.drop_table('tenant_subscription_history')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_system_role'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_portal_users_tenant_id'), table_name='portal_users')
    op.drop_index(op.f('ix_portal_users_manager_id'), table_name='portal_users')
    op.drop_index(op.f('ix_portal_users_email'), table_name='portal_users')
    op.drop_index('idx_portal_user_tenant_id', table_name='portal_users')
    op.drop_index('idx_portal_user_email', table_name='portal_users')
    op.drop_table('portal_users')
    op.drop_index(op.f('ix_tenants_subscription_plan_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_pm_admin_users_email'), table_name='pm_admin_users')
    op.drop_table('pm_admin_users')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_date'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_platform'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_location'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_is_remote'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_import_batch_id'), table_name='job_postings')
    op.drop_index('idx_job_posting_skills', table_name='job_postings', postgresql_using='gin')
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.drop_index('idx_job_posting_platform_external', table_name='job_postings')
    op.drop_index('idx_job_posting_keywords', table_name='job_postings', postgresql_using='gin')
    op.drop_index('idx_job_posting_embedding', table_name='job_postings', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_job_import_batches_platform'), table_name='job_import_batches')
    op.drop_index(op.f('ix_job_import_batches_import_status'), table_name='job_import_batches')
    op.drop_index(op.f('ix_job_import_batches_batch_id'), table_name='job_import_batches')
    op.drop_index('idx_job_import_batch_status', table_name='job_import_batches')
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.drop_index('idx_job_import_batch_platform', table_name='job_import_batches')
    op.drop_table('job_import_batches')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
