"""add_job_matching_tables

Revision ID: 8556f8b85cae
Revises: 3be0423032a8
Create Date: 2025-11-16 12:07:14.613373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '8556f8b85cae'
down_revision: Union[str, Sequence[str], None] = '3be0423032a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('import_source', sa.String(length=100), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('new_jobs', sa.Integer(), nullable=True),
    sa.Column('updated_jobs', sa.Integer(), nullable=True),
    sa.Column('failed_jobs', sa.Integer(), nullable=True),
    sa.Column('import_status', sa.String(length=50), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.create_index('idx_job_import_batch_tenant_status', 'job_import_batches', ['tenant_id', 'import_status'], unique=False)
    op.create_index(op.f('ix_job_import_batches_batch_id'), 'job_import_batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_job_import_batches_import_status'), 'job_import_batches', ['import_status'], unique=False)
    op.create_index(op.f('ix_job_import_batches_tenant_id'), 'job_import_batches', ['tenant_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_range', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('experience_required', sa.String(length=100), nullable=True),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_posting_embedding', 'job_postings', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_job_posting_keywords', 'job_postings', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    op.create_index('idx_job_posting_skills', 'job_postings', ['skills'], unique=False, postgresql_using='gin')
    op.create_index('idx_job_posting_tenant_platform_external', 'job_postings', ['tenant_id', 'platform', 'external_job_id'], unique=True)
    op.create_index(op.f('ix_job_postings_import_batch_id'), 'job_postings', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_job_postings_is_remote'), 'job_postings', ['is_remote'], unique=False)
    op.create_index(op.f('ix_job_postings_location'), 'job_postings', ['location'], unique=False)
    op.create_index(op.f('ix_job_postings_platform'), 'job_postings', ['platform'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_date'), 'job_postings', ['posted_date'], unique=False)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_index(op.f('ix_job_postings_tenant_id'), 'job_postings', ['tenant_id'], unique=False)
    op.create_table('candidate_job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('skill_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('experience_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('location_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('salary_match_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('semantic_similarity', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('matched_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('missing_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('match_reasons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.create_index('idx_candidate_job_match_unique', 'candidate_job_matches', ['candidate_id', 'job_posting_id'], unique=True)
    op.create_index(op.f('ix_candidate_job_matches_candidate_id'), 'candidate_job_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_job_posting_id'), 'candidate_job_matches', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_match_score'), 'candidate_job_matches', ['match_score'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_status'), 'candidate_job_matches', ['status'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('applied_via', sa.String(length=50), nullable=True),
    sa.Column('applied_by_user_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('screened_at', sa.DateTime(), nullable=True),
    sa.Column('interviewed_at', sa.DateTime(), nullable=True),
    sa.Column('offer_received_at', sa.DateTime(), nullable=True),
    sa.Column('offer_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.create_index('idx_job_application_candidate_status', 'job_applications', ['candidate_id', 'application_status'], unique=False)
    op.create_index('idx_job_application_unique', 'job_applications', ['candidate_id', 'job_posting_id'], unique=True)
    op.create_index(op.f('ix_job_applications_application_status'), 'job_applications', ['application_status'], unique=False)
    op.create_index(op.f('ix_job_applications_candidate_id'), 'job_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_applications_job_posting_id'), 'job_applications', ['job_posting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_job_posting_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_candidate_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_application_status'), table_name='job_applications')
    op.drop_index('idx_job_application_unique', table_name='job_applications')
    op.drop_index('idx_job_application_candidate_status', table_name='job_applications')
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_candidate_job_matches_status'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_match_score'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_job_posting_id'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_candidate_id'), table_name='candidate_job_matches')
    op.drop_index('idx_candidate_job_match_unique', table_name='candidate_job_matches')
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.drop_table('candidate_job_matches')
    op.drop_index(op.f('ix_job_postings_tenant_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_date'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_platform'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_location'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_is_remote'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_import_batch_id'), table_name='job_postings')
    op.drop_index('idx_job_posting_tenant_platform_external', table_name='job_postings')
    op.drop_index('idx_job_posting_skills', table_name='job_postings', postgresql_using='gin')
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.drop_index('idx_job_posting_keywords', table_name='job_postings', postgresql_using='gin')
    op.drop_index('idx_job_posting_embedding', table_name='job_postings', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_job_import_batches_tenant_id'), table_name='job_import_batches')
    op.drop_index(op.f('ix_job_import_batches_import_status'), table_name='job_import_batches')
    op.drop_index(op.f('ix_job_import_batches_batch_id'), table_name='job_import_batches')
    op.drop_index('idx_job_import_batch_tenant_status', table_name='job_import_batches')
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.drop_table('job_import_batches')
    # ### end Alembic commands ###
