"""Add tailored_resumes table

Revision ID: e6adbe9f8003
Revises: e835e16b0cf7
Create Date: 2025-12-14 12:54:18.377824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6adbe9f8003'
down_revision: Union[str, Sequence[str], None] = 'e835e16b0cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailored_resumes',
    sa.Column('tailor_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='tailoredresumestatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processing_step', sa.String(length=50), nullable=True),
    sa.Column('processing_progress', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('original_resume_content', sa.Text(), nullable=False),
    sa.Column('original_resume_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tailored_resume_content', sa.Text(), nullable=True),
    sa.Column('tailored_resume_html', sa.Text(), nullable=True),
    sa.Column('tailored_resume_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('original_match_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('tailored_match_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('score_improvement', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_company', sa.String(length=255), nullable=True),
    sa.Column('job_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('job_description_snippet', sa.Text(), nullable=True),
    sa.Column('matched_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('missing_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('added_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('iterations_used', sa.Integer(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_candidate_id'), 'tailored_resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_job_posting_id'), 'tailored_resumes', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_status'), 'tailored_resumes', ['status'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_tailor_id'), 'tailored_resumes', ['tailor_id'], unique=True)
    op.create_index(op.f('ix_tailored_resumes_tenant_id'), 'tailored_resumes', ['tenant_id'], unique=False)
    op.drop_index(op.f('idx_candidate_job_match_candidate_score'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_candidate_job_match_score_desc'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_job_application_applied_at_desc'), table_name='job_applications')
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.drop_index(op.f('idx_job_import_batch_started_at_desc'), table_name='job_import_batches')
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_index(op.f('idx_job_posting_posted_date_desc'), table_name='job_postings')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('idx_job_posting_posted_date_desc'), 'job_postings', [sa.literal_column('posted_date DESC')], unique=False)
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_job_import_batch_started_at_desc'), 'job_import_batches', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.create_index(op.f('idx_job_application_applied_at_desc'), 'job_applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_score_desc'), 'candidate_job_matches', [sa.literal_column('match_score DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_candidate_score'), 'candidate_job_matches', ['candidate_id', sa.literal_column('match_score DESC')], unique=False)
    op.drop_index(op.f('ix_tailored_resumes_tenant_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_tailor_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_status'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_job_posting_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_candidate_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    # ### end Alembic commands ###
