"""add_scrape_queue_and_role_normalization_tables

Revision ID: e835e16b0cf7
Revises: 402591f219c9
Create Date: 2025-12-12 20:04:21.756169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e835e16b0cf7'
down_revision: Union[str, Sequence[str], None] = '402591f219c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('total_jobs_scraped', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_platforms_is_active'), 'scraper_platforms', ['is_active'], unique=False)
    op.create_index(op.f('ix_scraper_platforms_name'), 'scraper_platforms', ['name'], unique=True)
    op.create_table('session_platform_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_imported', sa.Integer(), nullable=True),
    sa.Column('jobs_skipped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['scraper_platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['scrape_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'platform_id', name='uq_session_platform')
    )
    op.create_index('idx_session_platform_status', 'session_platform_status', ['session_id', 'status'], unique=False)
    op.create_index(op.f('ix_session_platform_status_platform_id'), 'session_platform_status', ['platform_id'], unique=False)
    op.create_index(op.f('ix_session_platform_status_session_id'), 'session_platform_status', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_platform_status_status'), 'session_platform_status', ['status'], unique=False)
    op.drop_index(op.f('idx_candidate_job_match_candidate_score'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_candidate_score', 'candidate_job_matches', ['candidate_id', 'match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_candidate_job_match_score_desc'), table_name='candidate_job_matches')
    op.create_index('idx_candidate_job_match_score_desc', 'candidate_job_matches', ['match_score'], unique=False, postgresql_ops={'match_score': 'DESC'})
    op.drop_index(op.f('idx_job_application_applied_at_desc'), table_name='job_applications')
    op.create_index('idx_job_application_applied_at_desc', 'job_applications', ['applied_at'], unique=False, postgresql_ops={'applied_at': 'DESC'})
    op.drop_index(op.f('idx_job_import_batch_started_at_desc'), table_name='job_import_batches')
    op.create_index('idx_job_import_batch_started_at_desc', 'job_import_batches', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_index(op.f('idx_job_posting_posted_date_desc'), table_name='job_postings')
    op.create_index('idx_job_posting_posted_date_desc', 'job_postings', ['posted_date'], unique=False, postgresql_ops={'posted_date': 'DESC'})
    op.add_column('scrape_sessions', sa.Column('platforms_total', sa.Integer(), nullable=True))
    op.add_column('scrape_sessions', sa.Column('platforms_completed', sa.Integer(), nullable=True))
    op.add_column('scrape_sessions', sa.Column('platforms_failed', sa.Integer(), nullable=True))
    op.add_column('scrape_sessions', sa.Column('session_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_sessions', 'session_notes')
    op.drop_column('scrape_sessions', 'platforms_failed')
    op.drop_column('scrape_sessions', 'platforms_completed')
    op.drop_column('scrape_sessions', 'platforms_total')
    op.drop_index('idx_job_posting_posted_date_desc', table_name='job_postings', postgresql_ops={'posted_date': 'DESC'})
    op.create_index(op.f('idx_job_posting_posted_date_desc'), 'job_postings', [sa.literal_column('posted_date DESC')], unique=False)
    op.drop_index('idx_job_import_batch_started_at_desc', table_name='job_import_batches', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_job_import_batch_started_at_desc'), 'job_import_batches', [sa.literal_column('started_at DESC')], unique=False)
    op.drop_index('idx_job_application_applied_at_desc', table_name='job_applications', postgresql_ops={'applied_at': 'DESC'})
    op.create_index(op.f('idx_job_application_applied_at_desc'), 'job_applications', [sa.literal_column('applied_at DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_score_desc', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_score_desc'), 'candidate_job_matches', [sa.literal_column('match_score DESC')], unique=False)
    op.drop_index('idx_candidate_job_match_candidate_score', table_name='candidate_job_matches', postgresql_ops={'match_score': 'DESC'})
    op.create_index(op.f('idx_candidate_job_match_candidate_score'), 'candidate_job_matches', ['candidate_id', sa.literal_column('match_score DESC')], unique=False)
    op.drop_index(op.f('ix_session_platform_status_status'), table_name='session_platform_status')
    op.drop_index(op.f('ix_session_platform_status_session_id'), table_name='session_platform_status')
    op.drop_index(op.f('ix_session_platform_status_platform_id'), table_name='session_platform_status')
    op.drop_index('idx_session_platform_status', table_name='session_platform_status')
    op.drop_table('session_platform_status')
    op.drop_index(op.f('ix_scraper_platforms_name'), table_name='scraper_platforms')
    op.drop_index(op.f('ix_scraper_platforms_is_active'), table_name='scraper_platforms')
    op.drop_table('scraper_platforms')
    # ### end Alembic commands ###
