/**
 * Portal Types Barrel Export
 */

export type {
  PortalUser,
  LoginRequest,
  LoginResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
} from './auth';

export type {
  Job,
  JobCreateRequest,
  JobUpdateRequest,
  JobListResponse,
  Candidate,
  CandidateCreateRequest,
  CandidateUpdateRequest,
  CandidateListResponse,
  Application,
  ApplicationCreateRequest,
  ApplicationUpdateRequest,
  ApplicationListResponse,
  Interview,
  InterviewCreateRequest,
  InterviewUpdateRequest,
  InterviewListResponse,
  PortalUserBasic,
  PortalUserFull,
  UserCreateRequest,
  UserUpdateRequest,
  UserListResponse,
  ResetPasswordRequest,
  Role,
  Permission,
  RoleListResponse,
  DashboardStats,
  TenantUsageStats,
  ApiError,
  PaginationParams,
  FilterParams,
} from './entities';

export type {
  CandidateInvitation,
  InvitationWithRelations,
  InvitationAuditLog,
  CandidateDocument,
  InvitationCreateRequest,
  InvitationUpdateRequest,
  InvitationListParams,
  InvitationListResponse,
  InvitationStatsResponse,
  InvitationReviewRequest,
  OnboardingSubmissionRequest,
  OnboardingSubmissionResponse,
  DocumentUploadResponse,
  BulkInvitationRequest,
  BulkInvitationResponse,
  InvitationFilters,
  InvitationSort,
  InvitationStatus,
  OnboardingType,
} from './invitation';

export type {
  Document,
  DocumentListItem,
  DocumentListResponse,
  DocumentUploadRequest,
  DocumentResponse,
  DocumentUrlResponse,
  DocumentVerifyRequest,
  DocumentStats,
  DocumentFilters,
  PublicDocumentUploadRequest,
  DocumentUploadProgress,
  DocumentType,
  StorageBackend,
} from './document';

export {
  DOCUMENT_TYPE_LABELS,
  DOCUMENT_TYPE_ICONS,
  MAX_FILE_SIZE,
  ALLOWED_FILE_TYPES,
  ALLOWED_FILE_EXTENSIONS,
} from './document';

export type {
  UserBasicInfo,
  TeamMember,
  TeamMemberWithCounts,
  ManagerWithCount,
  TeamHierarchyResponse,
  AvailableManagersResponse,
  ManagersListResponse,
  TeamMembersResponse,
  TeamMembersWithCountsResponse,
  AssignManagerRequest,
  AssignManagerResponse,
  RemoveManagerRequest,
  RemoveManagerResponse,
} from './team';

export type {
  UserInfo,
  AssignmentType,
  AssignmentStatus,
  CandidateAssignment,
  AssignmentNotification,
  AssignCandidateRequest,
  AssignCandidateResponse,
  ReassignCandidateRequest,
  ReassignCandidateResponse,
  UnassignCandidateRequest,
  UnassignCandidateResponse,
  CandidateAssignmentsResponse,
  CandidateInfo,
  UserAssignedCandidatesResponse,
  AssignmentHistoryResponse,
  NotificationsResponse,
  MarkNotificationReadRequest,
  MarkNotificationReadResponse,
  MarkAllNotificationsReadResponse,
  UserCandidatesFilters,
  AssignmentHistoryFilters,
  NotificationsFilters,
} from './assignment';

export type {
  OnboardingStatus,
  OnboardingUserInfo,
  CandidateOnboardingInfo,
  OnboardCandidateRequest,
  OnboardCandidateResponse,
  ApproveCandidateRequest,
  ApproveCandidateResponse,
  RejectCandidateRequest,
  RejectCandidateResponse,
  UpdateOnboardingStatusRequest,
  UpdateOnboardingStatusResponse,
  OnboardingCandidatesFilters,
  OnboardingCandidatesResponse,
  OnboardingStats,
  OnboardingStatsFilters,
} from './onboarding';

export type {
  JobPosting,
  JobMatch,
  JobMatchListResponse,
  JobMatchStats,
  GenerateMatchesRequest,
  GenerateMatchesResponse,
  JobMatchFilters,
  MatchGrade,
  GradeBadgeConfig,
} from './jobMatch';

export type {
  TailorStatus,
  ExportFormat,
  TailoredResume,
  TailorImprovement,
  SkillComparison,
  TailorResumeRequest,
  TailorFromMatchRequest,
  ExportResumeRequest,
  TailorResumeResponse,
  TailoredResumeListResponse,
  TailorStatsResponse,
  CompareResponse,
  TailorDialogState,
  TailorProgressState,
} from './tailoredResume';

export type {
  SubmissionStatus,
  RateType,
  InterviewType,
  PriorityLevel,
  ActivityType,
  SubmissionCandidate,
  SubmissionJob,
  SubmissionUser,
  SubmissionActivity,
  Submission,
  SubmissionCreateInput,
  SubmissionUpdateInput,
  SubmissionStatusUpdateInput,
  SubmissionInterviewScheduleInput,
  SubmissionActivityCreateInput,
  SubmissionFilters,
  SubmissionListResponse,
  SubmissionStats,
  SubmissionFollowUp,
  SubmissionFollowUpsResponse,
  QuickSubmitData,
} from './submission';

export {
  SUBMISSION_STATUSES,
  RATE_TYPES,
  INTERVIEW_TYPES,
  PRIORITY_LEVELS,
  ACTIVITY_TYPES,
  STATUS_LABELS,
  STATUS_COLORS,
  PRIORITY_COLORS,
  TERMINAL_STATUSES,
  ACTIVE_STATUSES,
  VALID_STATUS_TRANSITIONS,
  isValidStatusTransition,
  getNextValidStatuses,
  isTerminalStatus,
  isActiveStatus,
} from './submission';